const assert = require('assert');
const fs = require('fs');
const app = fs.readFileSync(require.resolve('../app.js'), 'utf8');
const server = fs.readFileSync(require.resolve('../server.js'), 'utf8');
assert.match(app, /e\.code !== 'Space'/);
assert.match(app, /w\.addEventListener\('focusin', \(\) => focusWin\(w\)\)/);
assert.match(fs.readFileSync(require.resolve('../content-first.css'), 'utf8'), /\.lunix-desktop-window:not\(\.active\) iframe \{ pointer-events: none; \}/);
assert.match(app, /video src=.*controls autoplay/);
assert.match(app, /ext === 'md'/);
assert.match(app, /actionLabel: 'Open preview'/);
assert.match(app, /nodusClient\.sessions\.preview/);
assert.match(app, /function openRuntimePreview\(url, port\)/);
assert.match(app, /previewTarget = \{ url: parsed\.href/);
assert.match(app, /onAction: \(\) => openRuntimePreview\(preview\.url, preview\.port\)/);
assert.match(app, /frame\.src = previewTarget\.url/);
assert.doesNotMatch(app, /openBrowserUrl\(preview\.url\)/);
assert.match(server, /accept-ranges/);
assert.match(server, /\/api\/local\/raw/);
console.log('preview wiring ok');
