const assert = require('assert');
const fs = require('fs');
const bridge = fs.readFileSync(require.resolve('../web/bridge.js'), 'utf8');
const desktop = fs.readFileSync(require.resolve('../../desktop/app.js'), 'utf8');
const build = fs.readFileSync(require.resolve('../../scripts/build-web.mjs'), 'utf8');
const renderer = fs.readFileSync(require.resolve('../renderer.js'), 'utf8');
const html = fs.readFileSync(require.resolve('../index.html'), 'utf8');
const pkg = require('../package.json');

assert.match(desktop, /searchParams\.set\('sessionId', agentSession\.session\.id\)/);
assert.match(desktop, /Connect the Agent first/);
assert.match(bridge, /new WebSocket\(nodusSocket\(\), \['tty'\]\)/);
assert.match(bridge, /searchParams\.set\('target', 'workspace'\)/);
assert.match(bridge, /sendNodus\(id, '0' \+ data\)/);
assert.match(bridge, /columns: cols, rows/);
assert.match(bridge, /socketQueues/);
assert.match(bridge, /lunix-terminal-status/);
assert.match(desktop, /data-terminal-retry/);
assert.equal(pkg.dependencies['@wterm/dom'], '^0.3.0');
assert.match(renderer, /import \{ WTerm \} from '@wterm\/dom'/);
assert.match(renderer, /new WTerm\(el/);
assert.match(renderer, /window\.warp\.spawn\(id, 80, 24\)/);
assert.match(renderer, /window\.warp\.resize\(id, term\.cols, term\.rows\)/);
assert.match(renderer, /requestAnimationFrame\(\(\) => requestAnimationFrame/);
assert.match(renderer, /pending: \[\]/);
assert.match(renderer, /for \(const data of pane\.pending\.splice\(0\)\) writePane/);
assert.doesNotMatch(bridge, /status: 'ready'/);
assert.match(desktop, /theme=lunix&embed=1/);
assert.match(desktop, /opacity:0;transition:opacity \.16s ease/);
assert.match(desktop, /event\.data\.status === 'ready'/);
assert.match(renderer, /window\.warp\.write\(id, data\)/);
assert.match(renderer, /window\.warp\.resize\(id, cols, rows\)/);
assert.match(html, /dist\/terminal\.js/);
assert.match(html, /dist\/terminal\.css/);
assert.match(html, /wasm-unsafe-eval/);
assert.doesNotMatch(html, /warpui|warp_terminal|gpu_terminal/);
assert.match(build, /<base href="\/terminal\/">/);
assert.match(build, /\['web', 'dist'\]/);
console.log('Nodus workspace terminal bridge ok');
